/// @description 
// Particle code generated by CrystallineJS
// https://iwverve.github.io/crystalline/


// -------- Particle System --------
// Run this code at the beginning of your game
psys = part_system_create();
//part_system_depth(psys, -100);
part_system_depth(psys, layer_get_depth(layer_get_id("Particles")));


// -------- Particle Type --------
// Run this code at the beginning of your game
ptyp = part_type_create();
part_type_shape(ptyp, pt_shape_sphere);
part_type_color3(ptyp, 14935011, 15451781, 13161907);
part_type_alpha3(ptyp, 0, 0.4, 0);
part_type_life(ptyp, 100, 400);
part_type_size(ptyp, 0.5, 1, 0, 0);
part_type_speed(ptyp, 0.18, 0.5, 0.04, 0.1);
part_type_direction(ptyp, 270, 270, 0, 0);
part_type_orientation(ptyp, 270, 270, 0, 0, false);
part_type_gravity(ptyp, 0.01, 270);
part_type_blend(ptyp, true);


// -------- Particle Emitter --------
// Consistently creates particles
// Run this in the Create event of the object emitting the particles
pemi = part_emitter_create(psys);
part_emitter_region(psys, pemi, x, x+32, y, y+32, ps_shape_rectangle, ps_distr_linear);
part_emitter_stream(psys, pemi, ptyp, 1);






// -------- Particle Burst --------
// Creates particles once at a specific position, instead of constantly emitting them
// Run this whenever you want to burst the particles
//part_particles_create(global.psys, x, y, global.ptyp, 21);
